services:
  s-backoffice__db:
    image: postgres:15
    container_name: s_backoffice__db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: s_backoffice__db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - s_backoffice__network
      
  s-backoffice__storage:
    image: minio/minio:latest
    container_name: s_backoffice__storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secret123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - storage_data:/data
    networks:
      - s_backoffice__network

  s-backoffice__redis:
    image: redis:7.2-alpine
    container_name: s_backoffice__redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: secret_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - s_backoffice__network

volumes:
  db_data:
  storage_data:
  redis_data:
networks:
  s_backoffice__network:
    driver: bridge